### PR TITLE
GameState table

### PR DESCRIPTION
**Pull request by jiayuhan94**
Gamestate working. Need help with the style of the game state table so it stay the same. Not changing during the game.

NEED HELP ON THE GAME STATE TABLE STYLE

### CODE REVIEW

**Comment by edwardne** [comment]
Looks fine. I'll see what I can do to try and fix it

**Comment by edwardne** [comment]
I'm not quite sure what you mean by its not changing during the game. It seems to work fine for me. Both hits and misses are displayed for player and AI as you play the game.

**Comment by jiayuhan94** [comment]
Sorry this was kinda late. I was working on another assignment, so I wasnt
checking my email. What I mean the size of the table will change during the
game which will look pretty awkward. Havent figured out a way to fix that
yet.

**Comment by edwardne** [comment]
That's alight. I'm not sure how to fix it either but its just a minor issue

**Pull request merged**
