### PR TITLE
UML Diagram

### PR DESCRIPTION
**Pull request by geddingj**
Think it's what we want, let me know if something needs to be added.

### CODE REVIEW

**Comment by edwardne** [comment]
Looks good. Although I think it may be composition instead of aggregation between Ship and Coordinate. Part of the ship object is start and end which are Coordinates therefore the ship can't exist without it.

**Comment by geddingj** [comment]
Wait, so do I need to find a way to swap the direction of the box or just fill it in -- already forgot which name meant what

**Comment by edwardne** [comment]
You just need to fill it in. Sorry I didn't see your comment till now

**Comment by geddingj** [comment]
Alright, changes inbound

**Comment by geddingj** [comment]
Alright filled it in -- and found a scanner to boot.

**Comment by edwardne** [comment]
Nice! Much easier to read now.

**Pull request merged**
